const PostsActionTypes = {
    SELECT_SUBREDDIT: 'SELECT_SUBREDDIT',
    INVALIDATE_SUBREDDIT: 'INVALIDATE_SUBREDDIT',
    REQUEST_POSTS: 'REQUEST_POSTS',
    RECEIVE_POSTS: 'RECEIVE_POSTS'
};

export {
    PostsActionTypes
};